### ISSUE TITLE
sizzle URL for jquery?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sherpa#27]
Why does the info.json entry for "jquery-2.1.0" include URL http://sizzlejs.com?

**Comment by samreid** [comment]
Because jquery includes sizzlejs.  Here is the full text you are referring to, which says "includes Sizzle.js":

```js
  "jquery-2.1.0": {
    "text": [
      "jQuery JavaScript Library v2.1.0 (includes Sizzle.js)",
      "Copyright 2005, 2014 jQuery Foundation, Inc. and other contributors",
      "http://jquery.com/",
      "http://sizzlejs.com",
      "http://jquery.org/license"
    ],
    "license": "The MIT License",
    "usage": ["sim"]
  }
```

and here is a stackoverflow thread that says that sizzle is a component of jquery (see top answer):

http://stackoverflow.com/questions/15785978/what-is-the-advantages-of-using-javascript-sizzle-library

**Comment by pixelzoom** [comment]
Great, thanks.
