### ISSUE TITLE
delete sherpa/licenses/ ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sherpa#30]
What is the purpose of sherpa/licenses/ ?
Looks like these can easily get out of sync with info.json license links.
And there are things in here that aren't in info.json.
Can we just delete the entire directory, or are they needed by something?

Assigning to @samreid for comment, since I believe he create this dir.

**Comment by samreid** [comment]
At one point I thought the licenses themselves were being included in the minified HTML file.  It appears this is no longer the case and since our licenses are fairly standard (mostly MIT and SIL) this may not be necessary.  Do any of the licenses require us to copy the license to the HTML file?  If not, then I think we can get rid of these.

**Comment by pixelzoom** [comment]
#33 (include complete license text for all third-party libraries that require it) seems to indicate otherwise.

**Comment by samreid** [comment]
Whatever we decide to do here will be covered by #33, closing.
