### ISSUE TITLE
Update requirejs from 2.1.11 to 2.3.6

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#76]
This issue came out of the developer team "patterns" meeting on modules.

In https://github.com/phetsims/sherpa/issues/10 we moved from requirejs 2.1.10 to 2.1.11.  Since then 18 requirejs releases have been published and the latest version is 2.3.6.  The change logs are here: https://requirejs.org/docs/download.html#releasenotes and indicate bugfixes, updates and a performance improvement.  One of the notes says "If you are using 2.2, you are encouraged to update to 2.3.".  Also 2.2 reportedly got a speed boost: https://jrburke.com/2016/03/17/requirejs-2.2-alameda-1.0-released/

@jbphet pointed out that upgrading to the latest version may require a small amount of work if it is backward compatible.

@ariel-phet should someone be assigned to investigate?  If so, what priority?

**Comment by ariel-phet** [comment]
seems worthy of investigation since we are far behind, @chrisklus said he would be willing to investigate.

**Comment by chrisklus** [comment]
Update complete. I haven't run into trouble so far.

Steps taken:
* downloaded `require-2.3.6.js` from https://requirejs.org/docs/download.html to sherpa
* replaced
  ```js
  loadURL( '../sherpa/lib/require-2.1.11.js', 'js/{{REPOSITORY}}-{{QUALIFIER}}config.js' );
  ```
  with
  ```js
  loadURL( '../sherpa/lib/require-2.3.6.js', 'js/{{REPOSITORY}}-{{QUALIFIER}}config.js' );
  ```
  in `chipper/templates/sim-development.html`
* did a project-wide find and replace of `require-2.1.11.js` with `require-2.3.6.js`
* verified that all sims start up using phet-brand sim tests in aqua
* verified that several built sims start up
* removed `require-2.1.11.js` from sherpa
* pushed changes, notified slack dev-public channel

**Comment by chrisklus** [comment]
I see two issues on CT that were likely cause by these changes:

in dot:
```
dot : pageload : /tests/playground.html : load
Uncaught TypeError: config.urlArgs is not a function
TypeError: config.urlArgs is not a function
    at Object.nameToUrl (https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:1679:37)
    at makeModuleMap (https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:474:35)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:1379:35
    at eachProp (https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:98:21)
    at Object.configure (https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:1374:17)
    at requirejs (https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:1794:21)
    at Function.req.config (https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:1805:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/dot/js/dot-config.js:9:9
id: Bayes Chrome
Approximately 5/14/2019, 4:42:20 PM
```

in scenery:
```
scenery : pageload : /tests/playground.html : load
Uncaught TypeError: config.urlArgs is not a function
TypeError: config.urlArgs is not a function
    at Object.nameToUrl (https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:1679:37)
    at makeModuleMap (https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:474:35)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:1379:35
    at eachProp (https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:98:21)
    at Object.configure (https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:1374:17)
    at requirejs (https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:1794:21)
    at Function.req.config (https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/sherpa/lib/require-2.3.6.js:1805:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557873740546/scenery/js/config.js:9:9
id: Bayes Chrome
Approximately 5/14/2019, 4:42:20 PM
```

I'll investigate.

**Comment by chrisklus** [comment]
The new requirejs did not like our argument for urlArgs, so I used the example for cache busting from the requirejs docs, see https://requirejs.org/docs/api.html#config-urlArgs.

This seems to have fixed the problem. @jonathanolson is there anything else we need to do on our end to make this work (since the string changed), or is this all handled in requirejs? It seems to not be happy unless I include `'bust='` before the timestamp.

Assigning to @jonathanolson for review.

**Comment by samreid** [comment]
Kite was showing the same symptom, so I applied the same solution.  @chrisklus please review.

**Comment by jonathanolson** [comment]
Looks like it's working to me. Thanks!

**Comment by jbphet** [comment]
I think this may have broken the `sound.js` plugin.  I just saw a console warning about sounds not being supported when working on an unrelated problem in Balancing Act, and I set some breakpoints and found that the URL for the sound looks messed up.  The only thing I can think of that might be related is this upgrade of RequireJS.  @chrisklus - can you see if this is likely the culprit?  I can help if needed, but thought you could take a look first.

**Comment by chrisklus** [comment]
@samreid said:

>Kite was showing the same symptom, so I applied the same solution. @chrisklus please review.

Thanks @samreid, looks good.

@jonathanolson said:

>Looks like it's working to me. Thanks!

Sounds good, thanks @jonathanolson.

**Comment by chrisklus** [comment]
@jbphet said:

>I think this may have broken the `sound.js` plugin. I just saw a console warning about sounds not being supported when working on an unrelated problem in Balancing Act, and I set some breakpoints and found that the URL for the sound looks messed up. The only thing I can think of that might be related is this upgrade of RequireJS. @chrisklus - can you see if this is likely the culprit? I can help if needed, but thought you could take a look first.

This is indeed due to the the upgrade of requirejs, and it happens to be related to all of the other problems that have come up from this upgrade. I have a pretty good understanding of what's happening, I just haven't been able to figure out why yet.

At line 63 of `sound.js`, if we're not in built mode, then this else happens, which is supposed to append the cache buster args to the url of the sound file. 

```js
else {
  // add the cache buster args to the URL
  soundInfo.url += '?' + config.urlArgs;
  
  // provide the URL corresponding to the specified sound
  onload( soundInfo );
}
```

Instead of returning a string like `js/../../tambo/js/../sounds/empty_apartment_bedroom_06_resampled.mp3?bust=1557987678372` (which is what's returned when the plugin is working), the added bust is a function, so the resulting string is instead:

```js
"js/../../tambo/js/../sounds/empty_apartment_bedroom_06_resampled.mp3?function(id, url) {
                        return (url.indexOf('?') === -1 ? '?' : '&') + urlArgs;
                    }"
```

All of the relevant config files that I've looked at are correctly using chippers method to get the proper `urlArgs`, which looks like:

```js
// optional cache buster to make browser refresh load all included scripts, can be disabled with ?cacheBuster=false
urlArgs: phet.chipper.getCacheBusterArgs()
```

I've verified that the following lines of code from chipper are rendering an appropriate string:

```js
/**
 * Gets the cache buster args based on the provided query parameters.  By default it is:
 * ?bust=<number>
 * But this can be omitted if ?cacheBuster=false is provided
 * See https://github.com/phetsims/joist/issues/196
 * @returns {string}
 */
window.phet.chipper.getCacheBusterArgs = function() {
  return phet.chipper.queryParameters.cacheBuster ? ( 'bust=' +  (new Date()).getTime() ) : '';
};
```

always results in, e.g., `"bust=1557987688370"`

I think the trouble is going down in `require-2.3.6.js`. At line 1290, any string forms of `urlArgs` are converted into a function:

```js
// Convert old style urlArgs string to a function.
if (typeof cfg.urlArgs === 'string') {
  var urlArgs = cfg.urlArgs;
  cfg.urlArgs = function(id, url) {
      return (url.indexOf('?') === -1 ? '?' : '&') + urlArgs;
  };
}
```

Later on at line 1678, this function is interpreted to return the `urlArgs` back to a string in the function `nameToUrl`. I think this is the normal path that config goes through, which is why this isn't broken anywhere else in our code base that we've seen so far:

```js
return config.urlArgs && !/^blob\:/.test(url) ? url + config.urlArgs(moduleName, url) : url;
```

I verified that for all normal phet files, `config.urlArgs` evaluates back to the usual string like `bust=1557987688370`.

As seen above, "tambo" is part of the url string for the added sound, `js/../../tambo/js/../sounds/empty_apartment_bedroom_06_resampled.mp3`. At line 1678 above, I logged all urls that came through that line of code that contained the string "tambo", and only phet files came through, no sound files:

```
js/../../tambo/js/soundManager.js
js/../../tambo/js/soundManager.js
js/../../tambo/js/audioContextStateChangeMonitor.js
js/../../tambo/js/phetAudioContext.js
js/../../tambo/js/soundConstants.js
js/../../tambo/js/soundInfoDecoder.js
js/../../tambo/js/SoundLevelEnum.js
js/../../tambo/js/tambo.js
js/../../tambo/js/TamboQueryParameters.js
js/../../tambo/js/audioContextStateChangeMonitor.js
js/../../tambo/js/tambo.js
js/../../tambo/js/phetAudioContext.js
js/../../tambo/js/tambo.js
js/../../tambo/js/TamboQueryParameters.js
js/../../tambo/js/soundConstants.js
js/../../tambo/js/tambo.js
js/../../tambo/js/soundInfoDecoder.js
js/../../tambo/js/tambo.js
js/../../tambo/js/SoundLevelEnum.js
js/../../tambo/js/tambo.js
js/../../tambo/js/tambo.js
js/../../tambo/js/tambo.js
js/../../tambo/js/tambo.js
js/../../tambo/js/tambo.js
js/../../tambo/js/tambo.js
js/../../tambo/js/TamboQueryParameters.js
js/../../tambo/js/tambo.js
js/../../tambo/js/tambo.js
js/../../tambo/js/tambo.js
js/../../tambo/js/TamboQueryParameters.js
```

My guess is that for plugins, `config` is not going through this path, so `config.urlArgs` is never getting turned from a function back into a string, which is why we're seeing an entire function being appended like a string above. The one thing I haven't been able to catch is when `cfg.urlArgs` is actually turned into a function for the plugin, but I don't see that function code anywhere else, so I don't know how else that could be happening. The two code snippets from `require-2.3.6` that I pasted above are the only occurrences of `urlArgs`.

I'm out of steam for now, but will continue to investigate.

**Comment by samreid** [comment]
This patch seems to address the symptoms for me:

```
Index: js/requirejs-plugins/sound.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/requirejs-plugins/sound.js	(revision e95257acdfa58846bd4d2f9b5612c4042b3a38d8)
+++ js/requirejs-plugins/sound.js	(date 1558013447000)
@@ -62,7 +62,7 @@
       }
       else {
         // add the cache buster args to the URL
-        soundInfo.url += '?' + config.urlArgs;
+        soundInfo.url += config.urlArgs( name, baseUrl );
 
         // provide the URL corresponding to the specified sound
         onload( soundInfo );
```

If you agree this is the right way to go, we should investigate more the correct args to pass to the `urlArgs` function, and check around our other plugins to see if they need to adopt this pattern as well.

**Comment by chrisklus** [comment]
Hey thanks, @samreid - that'll do it. No sure why I was so obsessed with figuring out why this wasn't being evaluated within requirejs like the other usages.

**Comment by chrisklus** [comment]
>check around our other plugins to see if they need to adopt this pattern as well.

I checked out our other plugins that use urlArgs (image, string, mipmap), and they were all also broken.

I committed fixes for the usages I found, @samreid could you review?

**Comment by samreid** [comment]
I reviewed the code and runtime behavior of all occurrences of `config.urlArgs` and I could not see any problems.  I think this issue can be closed--but we'll want to keep our eyes peeled during the next round of QA testing from master.

**Comment by samreid** [comment]
On second thought, I'll reassign back to @chrisklus to see if there's anything else for this issue.

**Comment by chrisklus** [comment]
Thanks @samreid - I'm not seeing anything else suspicious on CT, so I'm ready to close.
